// <auto-generated />
using System;
using Apex.Catering.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Apex.Catering.Migrations
{
    [DbContext(typeof(CateringDbContext))]
    [Migration("20251118235120_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "8.0.20");

            modelBuilder.Entity("Apex.Catering.Data.FoodBooking", b =>
                {
                    b.Property<int>("FoodBookingId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int?>("ClintReferenceId")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("MenuId")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("NumberOfGuests")
                        .HasColumnType("INTEGER");

                    b.HasKey("FoodBookingId");

                    b.HasIndex("MenuId");

                    b.ToTable("FoodBookings");

                    b.HasData(
                        new
                        {
                            FoodBookingId = 1,
                            ClintReferenceId = 1001,
                            MenuId = 1,
                            NumberOfGuests = 50
                        },
                        new
                        {
                            FoodBookingId = 2,
                            ClintReferenceId = 1002,
                            MenuId = 2,
                            NumberOfGuests = 30
                        },
                        new
                        {
                            FoodBookingId = 3,
                            ClintReferenceId = 1003,
                            MenuId = 3,
                            NumberOfGuests = 20
                        },
                        new
                        {
                            FoodBookingId = 4,
                            ClintReferenceId = 1004,
                            MenuId = 1,
                            NumberOfGuests = 40
                        });
                });

            modelBuilder.Entity("Apex.Catering.Data.FoodItem", b =>
                {
                    b.Property<int>("FoodItemId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<decimal>("UnitPrice")
                        .HasColumnType("TEXT");

                    b.HasKey("FoodItemId");

                    b.ToTable("FoodItems");

                    b.HasData(
                        new
                        {
                            FoodItemId = 1,
                            Description = "Chicken Curry",
                            UnitPrice = 8.50m
                        },
                        new
                        {
                            FoodItemId = 2,
                            Description = "Beef Stroganoff",
                            UnitPrice = 9.00m
                        },
                        new
                        {
                            FoodItemId = 3,
                            Description = "Vegetable Stir Fry",
                            UnitPrice = 7.00m
                        },
                        new
                        {
                            FoodItemId = 4,
                            Description = "Caesar Salad",
                            UnitPrice = 6.50m
                        },
                        new
                        {
                            FoodItemId = 5,
                            Description = "Grilled Salmon",
                            UnitPrice = 12.00m
                        },
                        new
                        {
                            FoodItemId = 6,
                            Description = "Pasta Primavera",
                            UnitPrice = 8.00m
                        },
                        new
                        {
                            FoodItemId = 7,
                            Description = "Roast Lamb",
                            UnitPrice = 11.00m
                        },
                        new
                        {
                            FoodItemId = 8,
                            Description = "Vegetable Lasagna",
                            UnitPrice = 9.50m
                        });
                });

            modelBuilder.Entity("Apex.Catering.Data.Menu", b =>
                {
                    b.Property<int>("MenuId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("MenuName")
                        .HasMaxLength(30)
                        .HasColumnType("TEXT");

                    b.HasKey("MenuId");

                    b.ToTable("Menus");

                    b.HasData(
                        new
                        {
                            MenuId = 1,
                            MenuName = "Standard Buffet"
                        },
                        new
                        {
                            MenuId = 2,
                            MenuName = "Vegetarian Delight"
                        },
                        new
                        {
                            MenuId = 3,
                            MenuName = "Seafood Special"
                        });
                });

            modelBuilder.Entity("Apex.Catering.Data.MenuFoodItem", b =>
                {
                    b.Property<int>("MenuId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("FoodItemId")
                        .HasColumnType("INTEGER");

                    b.HasKey("MenuId", "FoodItemId");

                    b.HasIndex("FoodItemId");

                    b.ToTable("MenuFoodItems");

                    b.HasData(
                        new
                        {
                            MenuId = 1,
                            FoodItemId = 1
                        },
                        new
                        {
                            MenuId = 1,
                            FoodItemId = 2
                        },
                        new
                        {
                            MenuId = 1,
                            FoodItemId = 4
                        },
                        new
                        {
                            MenuId = 1,
                            FoodItemId = 5
                        },
                        new
                        {
                            MenuId = 2,
                            FoodItemId = 3
                        },
                        new
                        {
                            MenuId = 2,
                            FoodItemId = 4
                        },
                        new
                        {
                            MenuId = 2,
                            FoodItemId = 6
                        },
                        new
                        {
                            MenuId = 2,
                            FoodItemId = 8
                        },
                        new
                        {
                            MenuId = 3,
                            FoodItemId = 5
                        },
                        new
                        {
                            MenuId = 3,
                            FoodItemId = 7
                        },
                        new
                        {
                            MenuId = 3,
                            FoodItemId = 4
                        });
                });

            modelBuilder.Entity("Apex.Catering.Data.FoodBooking", b =>
                {
                    b.HasOne("Apex.Catering.Data.Menu", "Menu")
                        .WithMany("FoodBookings")
                        .HasForeignKey("MenuId");

                    b.Navigation("Menu");
                });

            modelBuilder.Entity("Apex.Catering.Data.MenuFoodItem", b =>
                {
                    b.HasOne("Apex.Catering.Data.FoodItem", "FoodItem")
                        .WithMany("MenuFoodItem")
                        .HasForeignKey("FoodItemId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Apex.Catering.Data.Menu", "Menu")
                        .WithMany("MenuFoodItems")
                        .HasForeignKey("MenuId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("FoodItem");

                    b.Navigation("Menu");
                });

            modelBuilder.Entity("Apex.Catering.Data.FoodItem", b =>
                {
                    b.Navigation("MenuFoodItem");
                });

            modelBuilder.Entity("Apex.Catering.Data.Menu", b =>
                {
                    b.Navigation("FoodBookings");

                    b.Navigation("MenuFoodItems");
                });
#pragma warning restore 612, 618
        }
    }
}
